---
# Configureation information for running VCF web server

ref:
  - sample: NA00001
    description: Test Genome
    genome: biodata:/GRCh37/seq/GRCh37.fa
    genome-alts: []
    variants: test/data/phasing-reference.vcf
    intervals: test/data/phasing-reference-regions.bed
    default-compare: test/data/phasing-contestant.vcf

params:
  web:
    xprize: true
    google-analytics: null
  subsample:
    method: k-means
    count: 400000

remote:
  public:
    - /Home/Public/chapmanb/xprize
  biodata: /Home/Public/chapmanb/biodata

dir:
  cache: "tmp/cache"
  work: "tmp"

program:
  gemini: gemini
  vep: ~/install/variant_effect_predictor
