---
# Configureation information for running VCF web server

ref:
  - sample: NA00001
    description: Test Genome
    genome: biodata:/GRCh37/seq/GRCh37.fa
    genome-alts: []

params:
  subsample:
    method: k-means
    count: 400000

remote:
  public:
    - /Home/Public/chapmanb/xprize
  biodata: /Home/Public/chapmanb/biodata

dir:
  cache: "tmp/cache"
  work: "tmp"
